//  IMPLEMENTATION OF THE IF STATEMENT

let condition = 1 < 0;
if (condition){
    console.log("Runs the code")
} else{
    console.log("Else conddition runs..")
}

//  Implement another example using gender
 let gender = "f";
 if (gender == "M") {
    console.log("IT A MALE");
// apply the elseif condition to capture othe condition
 } else if (gender == "f"){
    console.log("it a female")
 } else {
    console.log("Unknown")
 }